[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "cd api && pip install -r requirements.txt",
  "cd web && npm install"
]

[phases.build]
cmds = [
  "cd web && npm run build"
]

[start]
cmd = "cd api && python run.py"

